### ISSUE TITLE
Putting each CSS style on its own line

### ISSUE THREAD

**Issue by zannain** [ReniDim/prj-rev-bwfs-dasmoto#5]
When writing CSS, [best practices](https://google.github.io/styleguide/htmlcssguide.html#CSS_Style_Rules) dictate that each style should be on its own line. This makes the styles easier to read.

_Currently_
```css
 #brushes {
   font-family: Helvetica; font-size: 32px; font-weight: bold; color:white;background-color: mediumspringgreen;
 }
```

_With each style on its own line_
```css
 #brushes {
   font-family: Helvetica; 
   font-size: 32px; 
   font-weight: bold; 
   color:white;
   background-color: mediumspringgreen;
 }
```
